### ISSUE TITLE
program nelimitat

### ISSUE THREAD

**Issue by robi09** [Codeinwp/woga#23]
La program pe index ar trebuii sa se afiseze posturi nelimita, ci nu doar 4.

**Comment by andreitripon** [comment]
in demo si la mine pe local observ ca se afiseaza mai mult de 4 posturi.

**Comment by ineagu** [comment]
cum merge cu tema asta ? e pus si pe demo ? cand punem tema pe site ?

**Comment by robi09** [comment]
Este gata tema. Trebuie sa fac pagina pe ti si update pe demo. O sa le fac in seara asta. 
--
Sent from myMail app for Android
Tuesday, 13 January 2015, 06:40PM +02:00 from Ionut Neagu <notifications@github.com>:
cum merge cu tema asta ? e pus si pe demo ? cand punem tema pe site ?
