### ISSUE TITLE
Zi curenta

### ISSUE THREAD

**Issue by robi09** [Codeinwp/woga#28]
Ziua curenta pe pagina de schedule face ca randul sa iasa din formatie, sa scazi dimensiunea la partea dreapta.

http://demo.themeisle.com/woga/?page_id=27
https://docs.google.com/file/d/0B_PXQJiDwwstMGEybXRvMk1Qc0k/edit?usp=drivesdk

**Comment by andreitripon** [comment]
Era o problema la background. Am rezolvat in Issue #25
