### ISSUE TITLE
widgetized footer

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/woga#34]
Footerul ar trebui sa fie o zona de widgets, este facut asa ?

**Comment by andreitripon** [comment]
widgeturile trebuie sa fie afisate pe coloane? Cate coloane?

**Comment by ineagu** [comment]
pai sa fie dinamic, minim 1 coloana, max 4. Adica daca are o coloana sa fie 100% width, daca are 2, 50/50, daca are 3, 30/30/30, daca are 4 : 25..... .

**Comment by andreitripon** [comment]
sa aibe posibilitatea de a seta din customizer cate coloane sa fie?

**Comment by robi09** [comment]
3 sunt ok.

**Comment by robi09** [comment]
Nu, 3 coloane sunt suficiente

**Comment by ineagu** [comment]
Nu se poate verifica in php/js cate widgeturi are si pune css dinamic? Ca sa ocupe tot spatiul daca sunt 2 de ex ?

**Comment by robi09** [comment]
Ba da se poate si asa. Ramane asa deci?

**Comment by andreitripon** [comment]
Deci, daca avem de ex: 3widgeturi sa fie 3 col; 4widgeturi = 4 col. ?
Dar daca un widget trebuie sa fie fullwidth, cum procedam?

**Comment by ineagu** [comment]
Adica, daca e un widget e 1-col.
